### ISSUE TITLE
wrs-avp-kmod does not compile on Linux kernel 4.7

### ISSUE THREAD

**Issue by TapioT** [Wind-River/titanium-server#1]
When compiling on latest Fedora 24 Cloud image, I got the error
make[1]: Entering directory '/usr/src/kernels/4.7.2-201.fc24.x86_64'

  CC [M]  /home/tapio/wrs-avp-kmod-1.2.3/avp_misc.o

  CC [M]  /home/tapio/wrs-avp-kmod-1.2.3/avp_net.o

/home/tapio/wrs-avp-kmod-1.2.3/avp_net.c: In function ‘avp_net_tx’:

/home/tapio/wrs-avp-kmod-1.2.3/avp_net.c:357:5: error: ‘struct net_device’ has no member named ‘trans_start’; did you mean ‘mem_start’?

  dev->trans_start = jiffies; /\* save the timestamp */

```
 ^~
```

The fix is explained in Linux kernel commit    4d659fcb20d3d3302b429c889a73a92ff2804b9a: replace the line with 
      netif_trans_update(dev);

**Comment by ian-jolliffewr** [comment]
Thanks for the report, will investigate and provide an update.

**Comment by ian-jolliffewr** [comment]
Hi Tapio;

The latest source tree for 16.10 now includes support for Linux Kernel 4.7 and has been posted here.
